filter:
  dependency_paths:
    - "src/Antlr/"
    - "vendor/"

build:
  tests:
    override:
      - command: './bin/phing unit'
        coverage:
          file:   'test/coverage.xml'
          format: 'php-clover'
